# Sonar project analysis properties overrides
sonar.projectKey=LizardByte_lizardbyte-common

# support the oldest standard used in lizardbyte projects
sonar.cfamily.reportingCppStandardOverride=c++17
